import {
  Activity,
  LayoutDashboard,
  Layers,
  Sparkles,
  Lock,
  SlidersHorizontal,
  Wrench,
} from 'lucide-react';
import { AINode } from '@/components/agent-nodes/AINode';
import { DenbegayeAgentNode } from '@/components/agent-nodes/DenbegayeAgentNode';
import { ToolNode } from '@/components/agent-nodes/ToolNode';
import { GroupNode } from '../components/GroupNode';

export type AgentNodeTypeField = {
  l: string;
  t: string;
  o?: string[];
  h?: string;
  d?: string | number | boolean | string[];
  required?: boolean;
  condition?: (configValues: Record<string, any>) => boolean;
};

export type AgentNodeType = {
  id: string;
  category: string;
  label: string;
  description?: string;
  config?: Record<string, unknown>;
  icon?: string | React.ComponentType<any>;
  bg?: string;
  dot?: string;
  badge?: string;
  bc?: string;
  btc?: string;
  must?: boolean;
  title?: string;
  sub?: string;
  configs?: AgentNodeTypeField[];
  acts?: string[];
};

export type SidebarItem = {
  id: string;
  label: string;
  icon: React.ComponentType<any>;
  href?: string;
};

export const availableNodeTypes: AgentNodeType[] = [
  // Existing nodes...
  {
    id: 'group',
    label: 'Group/Container',
    icon: LayoutDashboard,
    category: 'Core',
    bg: 'rgba(156,163,175,0.18)',
    dot: '#6b7280',
    badge: 'GROUP',
    bc: 'rgba(156,163,175,0.12)',
    btc: '#6b7280',
    must: false,
    title: 'Group Container',
    sub: 'Organize and group related nodes',
    configs: [],
    acts: ['Node grouping', 'Workflow organization'],
  },
  {
    id: 'ai-gemini',
    label: 'Google Gemini',
    icon: 'gemini',
    category: 'AI',
    bg: 'rgba(34,197,94,0.18)',
    dot: '#22c55e',
    badge: 'AI',
    bc: 'rgba(34,197,94,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'Google Gemini AI',
    sub: 'Advanced AI model from Google',
    configs: [
      { l: 'API Key', t: 'password', h: 'Google AI API key' },
      {
        l: 'Model',
        t: 'select',
        o: [
          'gemini-2.5-flash',
          'gemini-2.0-pro',
          'gemini-2.0-flash',
          'gemini-1.5-pro',
          'gemini-1.5-flash',
          'gemini-1.0-pro',
          'gemini-1.0-flash',
        ],
        d: 'gemini-2.5-flash',
        h: 'Google Gemini model version',
        required: true,
      },
      { l: 'Temperature', t: 'number', h: 'Creativity level (0-2)' },
      { l: 'Max Tokens', t: 'number', h: 'Maximum response length' },
      { l: 'System Prompt', t: 'textarea', h: 'Instructions for the AI', required: true },
      { l: 'Input Text', t: 'textarea', h: 'Text to process', required: true },
    ],
    acts: ['Text generation', 'Code generation', 'Analysis', 'Translation'],
  },
  {
    id: 'ai-openai',
    label: 'OpenAI GPT',
    icon: 'openai',
    category: 'AI',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'AI',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'OpenAI GPT Models',
    sub: 'GPT-4, GPT-3.5 and other OpenAI models',
    configs: [
      { l: 'API Key', t: 'password', h: 'OpenAI API key' },
      {
        l: 'Model',
        t: 'select',
        o: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-4', 'gpt-3.5-turbo'],
        h: 'GPT model version',
        required: true,
      },
      { l: 'Temperature', t: 'number', h: 'Creativity level (0-2)' },
      { l: 'Max Tokens', t: 'number', h: 'Maximum response length' },
      { l: 'System Prompt', t: 'textarea', h: 'Instructions for the AI', required: true },
      { l: 'Input Text', t: 'textarea', h: 'Text to process', required: true },
    ],
    acts: ['Text generation', 'Code generation', 'Analysis', 'Translation'],
  },
  {
    id: 'ai-anthropic',
    label: 'Anthropic Claude',
    icon: 'anthropic',
    category: 'AI',
    bg: 'rgba(245,158,11,0.18)',
    dot: '#f59e0b',
    badge: 'AI',
    bc: 'rgba(245,158,11,0.12)',
    btc: '#f59e0b',
    must: false,
    title: 'Anthropic Claude AI',
    sub: 'Claude 3 models from Anthropic',
    configs: [
      { l: 'API Key', t: 'password', h: 'Anthropic API key' },
      {
        l: 'Model',
        t: 'select',
        o: ['claude-3-5-sonnet-20241022', 'claude-3-5-haiku-20241022', 'claude-3-opus-20240229'],
        h: 'Claude model version',
        required: true,
      },
      { l: 'Temperature', t: 'number', h: 'Creativity level (0-1)' },
      { l: 'Max Tokens', t: 'number', h: 'Maximum response length' },
      { l: 'System Prompt', t: 'textarea', h: 'Instructions for the AI', required: true },
      { l: 'Input Text', t: 'textarea', h: 'Text to process', required: true },
    ],
    acts: ['Text generation', 'Code generation', 'Analysis', 'Translation'],
  },
  {
    id: 'ai-grok',
    label: 'Grok AI',
    icon: 'grok',
    category: 'AI',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'AI',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Grok AI by xAI',
    sub: 'Grok models from xAI',
    configs: [
      { l: 'API Key', t: 'password', h: 'xAI API key' },
      { l: 'Model', t: 'select', o: ['grok-beta', 'grok-vision-beta'], h: 'Grok model version' },
      { l: 'Temperature', t: 'number', h: 'Creativity level (0-2)' },
      { l: 'Max Tokens', t: 'number', h: 'Maximum response length' },
      { l: 'System Prompt', t: 'textarea', h: 'Instructions for the AI', required: true },
      { l: 'Input Text', t: 'textarea', h: 'Text to process', required: true },
    ],
    acts: ['Text generation', 'Code generation', 'Analysis', 'Translation'],
  },
  {
    id: 'ai-deepseek',
    label: 'DeepSeek AI',
    icon: 'deepseek',
    category: 'AI',
    bg: 'rgba(239,68,68,0.18)',
    dot: '#ef4444',
    badge: 'AI',
    bc: 'rgba(239,68,68,0.12)',
    btc: '#ef4444',
    must: false,
    title: 'DeepSeek AI Models',
    sub: 'OpenAI and Anthropic compatible DeepSeek models',
    configs: [
      { l: 'API Key', t: 'password', h: 'DeepSeek API key', required: true },
      {
        l: 'Compatibility',
        t: 'select',
        o: ['openai', 'anthropic'],
        h: 'DeepSeek compatibility mode for requests',
        required: true,
      },
      {
        l: 'Base URL',
        t: 'text',
        h: 'Use https://api.deepseek.com for OpenAI-compatible access or https://api.deepseek.com/anthropic for Anthropic-compatible access',
      },
      {
        l: 'Model',
        t: 'select',
        o: ['deepseek-v4-flash', 'deepseek-v4-pro', 'deepseek-chat', 'deepseek-reasoner'],
        h: 'DeepSeek model version \u2014 chat/reasoner models are deprecated on 2026/07/24',
        required: true,
      },
      { l: 'Temperature', t: 'number', h: 'Creativity level (0-2)' },
      { l: 'Max Tokens', t: 'number', h: 'Maximum response length' },
      { l: 'System Prompt', t: 'textarea', h: 'Instructions for the AI', required: true },
      { l: 'Input Text', t: 'textarea', h: 'Text to process', required: true },
    ],
    acts: ['Text generation', 'Code generation', 'Analysis', 'Translation'],
  },
  {
    id: 'trigger-webhook',
    label: 'Webhook Trigger',
    icon: 'webhook',
    category: 'Triggers',
    bg: 'rgba(139,92,246,0.18)',
    dot: '#8b5cf6',
    badge: 'TRIGGER',
    bc: 'rgba(139,92,246,0.12)',
    btc: '#8b5cf6',
    must: false,
    title: 'Webhook Trigger',
    sub: 'Start workflow from HTTP requests',
    configs: [
      { l: 'Endpoint Path', t: 'text', h: 'Custom webhook path' },
      {
        l: 'HTTP Method',
        t: 'select',
        o: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        h: 'HTTP method to listen for',
        required: true,
      },
      {
        l: 'Authentication',
        t: 'select',
        o: ['none', 'basic', 'bearer', 'api-key'],
        h: 'Authentication method',
        required: false,
      },
      { l: 'Secret Key', t: 'password', h: 'Secret for webhook verification' },
    ],
    acts: ['HTTP request handling', 'Data parsing', 'Authentication'],
  },
  {
    id: 'trigger-schedule',
    label: 'Schedule Trigger',
    icon: 'schedule',
    category: 'Triggers',
    bg: 'rgba(34,197,94,0.18)',
    dot: '#22c55e',
    badge: 'TRIGGER',
    bc: 'rgba(34,197,94,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'Scheduled Trigger',
    sub: 'Run workflow on a schedule',
    configs: [
      { l: 'Cron Expression', t: 'text', h: 'Cron schedule (e.g., 0 9 * * 1)' },
      { l: 'Timezone', t: 'text', h: 'Timezone (e.g., America/New_York)' },
      { l: 'Start Date', t: 'text', h: 'When to start the schedule' },
      { l: 'End Date', t: 'text', h: 'When to stop the schedule' },
    ],
    acts: ['Scheduled execution', 'Time-based triggers'],
  },
  {
    id: 'trigger-email',
    label: 'Email Trigger',
    icon: 'email',
    category: 'Triggers',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'TRIGGER',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'Email Trigger',
    sub: 'Start workflow when email arrives',
    configs: [
      { l: 'Email Address', t: 'text', h: 'Email to monitor' },
      { l: 'Subject Filter', t: 'text', h: 'Filter by subject keywords' },
      { l: 'Sender Filter', t: 'text', h: 'Filter by sender email' },
      { l: 'Poll Interval', t: 'number', h: 'Minutes between checks' },
    ],
    acts: ['Email monitoring', 'Message parsing', 'Attachment handling'],
  },
  {
    id: 'trigger-calendar-event',
    label: 'Calendar Event Trigger',
    icon: 'clock',
    category: 'Triggers',
    bg: 'rgba(34,197,94,0.18)',
    dot: '#22c55e',
    badge: 'TRIGGER',
    bc: 'rgba(34,197,94,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'Calendar Event Trigger',
    sub: 'Start workflows from calendar events',
    configs: [
      { l: 'Calendar ID', t: 'text', h: 'Calendar to monitor' },
      { l: 'Event Title Filter', t: 'text', h: 'Filter events by title' },
      { l: 'Start Window', t: 'text', h: 'Time window or upcoming range' },
      { l: 'Poll Interval', t: 'number', h: 'Minutes between checks' },
    ],
    acts: ['Calendar monitoring', 'Event triggers', 'Time-based workflows'],
  },
  {
    id: 'trigger-slack-event',
    label: 'Slack Event Trigger',
    icon: 'slack',
    category: 'Triggers',
    bg: 'rgba(74,21,122,0.18)',
    dot: '#4f46e5',
    badge: 'TRIGGER',
    bc: 'rgba(74,21,122,0.12)',
    btc: '#4f46e5',
    must: false,
    title: 'Slack Event Trigger',
    sub: 'Start workflows from Slack channel events',
    configs: [
      { l: 'Workspace', t: 'text', h: 'Slack workspace or app' },
      { l: 'Channel', t: 'text', h: 'Channel or conversation to monitor' },
      {
        l: 'Event Type',
        t: 'select',
        o: ['message', 'reaction', 'mention', 'file'],
        h: 'Slack event type',
        required: true,
      },
      { l: 'Keyword Filter', t: 'text', h: 'Filter messages by keyword' },
      { l: 'Poll Interval', t: 'number', h: 'Minutes between checks' },
    ],
    acts: ['Chat event monitoring', 'Slack automation', 'Notifications'],
  },
  {
    id: 'trigger-sms',
    label: 'SMS Trigger',
    icon: 'phone',
    category: 'Triggers',
    bg: 'rgba(6,182,212,0.18)',
    dot: '#06b6d4',
    badge: 'TRIGGER',
    bc: 'rgba(6,182,212,0.12)',
    btc: '#06b6d4',
    must: false,
    title: 'SMS Trigger',
    sub: 'Start workflows when an SMS message arrives',
    configs: [
      { l: 'Phone Number', t: 'text', h: 'Phone number to monitor' },
      { l: 'Provider', t: 'select', o: ['twilio', 'nexmo', 'plivo'], h: 'SMS provider' },
      { l: 'Keyword Filter', t: 'text', h: 'Filter message body by keyword' },
      { l: 'Poll Interval', t: 'number', h: 'Minutes between checks' },
    ],
    acts: ['SMS monitoring', 'Message routing', 'Alerting'],
  },
  {
    id: 'trigger-form-submission',
    label: 'Form Submission Trigger',
    icon: 'file-text',
    category: 'Triggers',
    bg: 'rgba(245,158,11,0.18)',
    dot: '#f59e0b',
    badge: 'TRIGGER',
    bc: 'rgba(245,158,11,0.12)',
    btc: '#f59e0b',
    must: false,
    title: 'Form Submission Trigger',
    sub: 'Start workflows when a form is submitted',
    configs: [
      { l: 'Form ID', t: 'text', h: 'ID of the form to monitor' },
      {
        l: 'Provider',
        t: 'select',
        o: ['typeform', 'google-forms', 'jotform'],
        h: 'Form provider',
        required: true,
      },
      { l: 'Field Filter', t: 'text', h: 'Field or value filter' },
      { l: 'Poll Interval', t: 'number', h: 'Minutes between checks' },
    ],
    acts: ['Form automation', 'Lead capture', 'Event triggers'],
  },
  {
    id: 'trigger-website-form',
    label: 'Website Form Trigger',
    icon: 'globe',
    category: 'Triggers',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'TRIGGER',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Website Form Trigger',
    sub: 'Start workflows from website form submissions',
    configs: [
      { l: 'Website URL', t: 'text', h: 'URL of the website to monitor' },
      { l: 'Form Selector', t: 'text', h: 'CSS selector for the form' },
      { l: 'Webhook URL', t: 'text', h: 'Webhook endpoint to receive form data' },
      { l: 'Field Mapping', t: 'textarea', h: 'JSON mapping of form fields' },
    ],
    acts: ['Website monitoring', 'Form capture', 'Lead generation'],
  },
  {
    id: 'trigger-manual',
    label: 'Manual Trigger',
    icon: 'wrench',
    category: 'Triggers',
    bg: 'rgba(156,163,175,0.18)',
    dot: '#6b7280',
    badge: 'TRIGGER',
    bc: 'rgba(156,163,175,0.12)',
    btc: '#6b7280',
    must: false,
    title: 'Manual Trigger',
    sub: 'Manually run workflows on demand',
    configs: [
      { l: 'Trigger Name', t: 'text', h: 'Name for this manual trigger' },
      { l: 'Description', t: 'textarea', h: 'Description of when to use this trigger' },
      { l: 'Input Schema', t: 'textarea', h: 'JSON schema for manual inputs' },
    ],
    acts: ['Manual execution', 'Testing', 'On-demand workflows'],
  },
  {
    id: 'trigger-chat-input',
    label: 'Chat Input Trigger',
    icon: 'message',
    category: 'Triggers',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'TRIGGER',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'Chat Input Trigger',
    sub: 'Start workflows from chat messages',
    configs: [
      {
        l: 'Chat Platform',
        t: 'select',
        o: ['slack', 'discord', 'telegram', 'web'],
        h: 'Chat platform',
        required: true,
      },
      { l: 'Channel/Room', t: 'text', h: 'Specific channel or room to monitor' },
      { l: 'Keyword Trigger', t: 'text', h: 'Keyword that triggers the workflow' },
      {
        l: 'Bot Mention Required',
        t: 'select',
        o: ['yes', 'no'],
        h: 'Require bot mention to trigger',
        required: true,
      },
    ],
    acts: ['Chat automation', 'Conversational workflows', 'Bot interactions'],
  },
  {
    id: 'core-http-request',
    label: 'HTTP Request',
    icon: 'http',
    category: 'Core',
    bg: 'rgba(156,163,175,0.18)',
    dot: '#6b7280',
    badge: 'HTTP',
    bc: 'rgba(156,163,175,0.12)',
    btc: '#6b7280',
    must: false,
    title: 'HTTP Request',
    sub: 'Make HTTP requests to APIs',
    configs: [
      { l: 'Method', t: 'select', o: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], h: 'HTTP method' },
      { l: 'URL', t: 'text', h: 'Request URL' },
      { l: 'Headers', t: 'textarea', h: 'JSON headers object' },
      { l: 'Body', t: 'textarea', h: 'Request body (JSON)' },
      { l: 'Timeout', t: 'number', h: 'Request timeout in seconds' },
      {
        l: 'Authentication',
        t: 'select',
        o: ['none', 'basic', 'bearer', 'api-key'],
        h: 'Auth method',
        required: false,
      },
    ],
    acts: ['API calls', 'Data fetching', 'Webhooks', 'Integration'],
  },
  {
    id: 'core-code-js',
    label: 'JavaScript Code',
    icon: 'javascript',
    category: 'Core',
    bg: 'rgba(245,158,11,0.18)',
    dot: '#f59e0b',
    badge: 'CODE',
    bc: 'rgba(245,158,11,0.12)',
    btc: '#f59e0b',
    must: false,
    title: 'JavaScript Code',
    sub: 'Execute custom JavaScript code',
    configs: [
      { l: 'Code', t: 'textarea', h: 'JavaScript code to execute' },
      { l: 'Input Data', t: 'textarea', h: 'JSON input data' },
      { l: 'Libraries', t: 'textarea', h: 'Comma-separated npm packages' },
    ],
    acts: ['Code execution', 'Data transformation', 'Custom logic'],
  },
  {
    id: 'core-code-python',
    label: 'Python Code',
    icon: 'python',
    category: 'Core',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'CODE',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'Python Code',
    sub: 'Execute custom Python code',
    configs: [
      { l: 'Code', t: 'textarea', h: 'Python code to execute' },
      { l: 'Input Data', t: 'textarea', h: 'JSON input data' },
      { l: 'Libraries', t: 'textarea', h: 'Comma-separated pip packages' },
    ],
    acts: ['Code execution', 'Data transformation', 'Custom logic'],
  },
  {
    id: 'core-set',
    label: 'Set Variable',
    icon: 'database',
    category: 'Core',
    bg: 'rgba(34,197,94,0.18)',
    dot: '#22c55e',
    badge: 'SET',
    bc: 'rgba(34,197,94,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'Set Variable',
    sub: 'Store values for later workflow use',
    configs: [
      {
        l: 'Expression',
        t: 'textarea',
        h: 'JavaScript expression or JSON object defining variables',
        required: true,
      },
    ],
    acts: ['Variable storage', 'Data passing', 'Workflow state'],
  },
  {
    id: 'logic-if',
    label: 'If/Else',
    icon: 'if',
    category: 'Logic',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'LOGIC',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Conditional Logic',
    sub: 'Execute different paths based on conditions',
    configs: [
      { l: 'Condition', t: 'textarea', h: 'JavaScript condition expression' },
      { l: 'Input Data', t: 'textarea', h: 'JSON data for condition evaluation' },
    ],
    acts: ['Conditional execution', 'Branching logic', 'Decision making'],
  },
  {
    id: 'logic-switch',
    label: 'Switch Case',
    icon: 'switch',
    category: 'Logic',
    bg: 'rgba(239,68,68,0.18)',
    dot: '#ef4444',
    badge: 'LOGIC',
    bc: 'rgba(239,68,68,0.12)',
    btc: '#ef4444',
    must: false,
    title: 'Switch Case',
    sub: 'Multiple conditional branches',
    configs: [
      { l: 'Expression', t: 'textarea', h: 'Value to switch on' },
      { l: 'Cases', t: 'textarea', h: 'JSON array of case values' },
    ],
    acts: ['Multi-branch logic', 'Value-based routing'],
  },
  {
    id: 'logic-loop',
    label: 'Loop',
    icon: 'loop',
    category: 'Logic',
    bg: 'rgba(34,197,94,0.18)',
    dot: '#22c55e',
    badge: 'LOGIC',
    bc: 'rgba(34,197,94,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'Loop/Iterator',
    sub: 'Iterate over arrays or collections',
    configs: [
      { l: 'Items', t: 'textarea', h: 'Array or collection to iterate' },
      { l: 'Max Iterations', t: 'number', h: 'Maximum loop iterations' },
    ],
    acts: ['Iteration', 'Batch processing', 'Data transformation'],
  },
  {
    id: 'logic-wait',
    label: 'Wait/Delay',
    icon: 'wait',
    category: 'Logic',
    bg: 'rgba(156,163,175,0.18)',
    dot: '#6b7280',
    badge: 'LOGIC',
    bc: 'rgba(156,163,175,0.12)',
    btc: '#6b7280',
    must: false,
    title: 'Wait/Delay',
    sub: 'Pause workflow execution',
    configs: [
      { l: 'Delay', t: 'number', h: 'Delay in seconds' },
      { l: 'Delay Type', t: 'select', o: ['fixed', 'random'], h: 'Fixed or random delay' },
    ],
    acts: ['Timing control', 'Rate limiting', 'Sequential execution'],
  },
  {
    id: 'action-email',
    label: 'Send Email',
    icon: 'email',
    category: 'Actions',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'EMAIL',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'Send Email',
    sub: 'Send emails via SMTP or services',
    configs: [
      {
        l: 'Provider',
        t: 'select',
        o: ['smtp', 'sendgrid', 'mailgun', 'ses'],
        h: 'Email service provider',
        required: true,
      },
      // SMTP Configuration Fields
      {
        l: 'SMTP Host',
        t: 'text',
        h: 'e.g., smtp.gmail.com',
        required: true,
        condition: (config: any) => config.provider === 'smtp',
      },
      {
        l: 'SMTP Port',
        t: 'number',
        h: 'e.g., 587 for Gmail',
        required: true,
        condition: (config: any) => config.provider === 'smtp',
      },
      {
        l: 'SMTP Secure',
        t: 'checkbox',
        h: 'Use TLS/SSL encryption',
        required: false,
        condition: (config: any) => config.provider === 'smtp',
      },
      {
        l: 'SMTP User',
        t: 'text',
        h: 'Your email address (e.g., your-email@gmail.com)',
        required: true,
        condition: (config: any) => config.provider === 'smtp',
      },
      {
        l: 'SMTP Password',
        t: 'password',
        h: 'Your password or app password for Gmail',
        required: true,
        condition: (config: any) => config.provider === 'smtp',
      },
      // SendGrid Configuration Fields
      {
        l: 'SendGrid API Key',
        t: 'password',
        h: 'Your SendGrid API key (SG.xxxxx)',
        required: true,
        condition: (config: any) => config.provider === 'sendgrid',
      },
      {
        l: 'SendGrid From Email',
        t: 'text',
        h: 'Verified sender email (e.g., noreply@domain.com)',
        required: true,
        condition: (config: any) => config.provider === 'sendgrid',
      },
      // Mailgun Configuration Fields
      {
        l: 'Mailgun API Key',
        t: 'password',
        h: 'Your Mailgun API key (key-xxxxx)',
        required: true,
        condition: (config: any) => config.provider === 'mailgun',
      },
      {
        l: 'Mailgun Domain',
        t: 'text',
        h: 'Your Mailgun domain (e.g., mg.yourdomain.com)',
        required: true,
        condition: (config: any) => config.provider === 'mailgun',
      },
      // AWS SES Configuration Fields
      {
        l: 'AWS Region',
        t: 'text',
        h: 'AWS region (e.g., us-east-1)',
        required: true,
        condition: (config: any) => config.provider === 'ses',
      },
      {
        l: 'AWS Access Key',
        t: 'password',
        h: 'AWS Access Key ID',
        required: true,
        condition: (config: any) => config.provider === 'ses',
      },
      {
        l: 'AWS Secret Key',
        t: 'password',
        h: 'AWS Secret Access Key',
        required: true,
        condition: (config: any) => config.provider === 'ses',
      },
      // Common Email Fields
      {
        l: 'From',
        t: 'text',
        h: 'Sender email address (optional if set in provider config)',
        condition: (config: any) => config.provider !== 'ses',
      },
      {
        l: 'To',
        t: 'text',
        h: 'Recipient email addresses (comma-separated for multiple)',
        required: true,
      },
      {
        l: 'Subject',
        t: 'text',
        h: 'Email subject line',
        required: true,
      },
      {
        l: 'Body',
        t: 'textarea',
        h: 'Email body (HTML or plain text)',
        required: true,
      },
      {
        l: 'Is HTML',
        t: 'checkbox',
        h: 'Treat body as HTML (checked) or plain text (unchecked)',
        required: false,
      },
      {
        l: 'Attachments',
        t: 'textarea',
        h: 'JSON array: [{"filename": "file.pdf", "url": "https://..."}, ...]',
        required: false,
      },
    ],
    acts: ['Email sending', 'Notifications', 'Marketing emails', 'Transactional emails'],
  },
  {
    id: 'action-webhook',
    label: 'Send Webhook',
    icon: 'webhook',
    category: 'Actions',
    bg: 'rgba(139,92,246,0.18)',
    dot: '#8b5cf6',
    badge: 'WEBHOOK',
    bc: 'rgba(139,92,246,0.12)',
    btc: '#8b5cf6',
    must: false,
    title: 'Send Webhook',
    sub: 'Send HTTP requests to external services',
    configs: [
      { l: 'URL', t: 'text', h: 'Webhook URL' },
      { l: 'Method', t: 'select', o: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], h: 'HTTP method' },
      { l: 'Headers', t: 'textarea', h: 'JSON headers object' },
      { l: 'Body', t: 'textarea', h: 'Request body data' },
      {
        l: 'Authentication',
        t: 'select',
        o: ['none', 'basic', 'bearer', 'api-key'],
        h: 'Auth method',
        required: false,
      },
    ],
    acts: ['API integration', 'External notifications', 'Data sync'],
  },
  {
    id: 'action-telegram',
    label: 'Telegram Bot',
    icon: 'telegram',
    category: 'Social Media',
    bg: 'rgba(56,178,172,0.18)',
    dot: '#38b2ac',
    badge: 'CHAT',
    bc: 'rgba(56,178,172,0.12)',
    btc: '#38b2ac',
    must: false,
    title: 'Telegram Bot',
    sub: 'Send messages via Telegram Bot API',
    configs: [
      { l: 'Bot Token', t: 'password', h: 'Telegram bot token' },
      { l: 'Chat ID', t: 'text', h: 'Telegram chat ID' },
      { l: 'Message', t: 'textarea', h: 'Message text' },
      { l: 'Parse Mode', t: 'select', o: ['text', 'markdown', 'html'], h: 'Message formatting' },
    ],
    acts: ['Bot messaging', 'Notifications', 'Chat automation'],
  },
  {
    id: 'action-whatsapp',
    label: 'WhatsApp',
    icon: 'whatsapp',
    category: 'Social Media',
    bg: 'rgba(37,211,102,0.18)',
    dot: '#22c55e',
    badge: 'CHAT',
    bc: 'rgba(37,211,102,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'WhatsApp Message',
    sub: 'Send messages via WhatsApp / Twilio',
    configs: [
      { l: 'Account SID', t: 'text', h: 'Twilio account SID' },
      { l: 'Auth Token', t: 'password', h: 'Twilio auth token' },
      { l: 'From', t: 'text', h: 'WhatsApp sender number' },
      { l: 'To', t: 'text', h: 'WhatsApp recipient number' },
      { l: 'Message', t: 'textarea', h: 'Text to send' },
    ],
    acts: ['Chat delivery', 'Notifications'],
  },
  {
    id: 'action-linkedin',
    label: 'LinkedIn',
    icon: 'linkedin',
    category: 'Social Media',
    bg: 'rgba(10,102,194,0.18)',
    dot: '#0a66c2',
    badge: 'SOCIAL',
    bc: 'rgba(10,102,194,0.12)',
    btc: '#0a66c2',
    must: false,
    title: 'LinkedIn Post',
    sub: 'Publish LinkedIn share updates',
    configs: [
      { l: 'Access Token', t: 'password', h: 'LinkedIn API token' },
      { l: 'Author URN', t: 'text', h: 'LinkedIn author urn' },
      { l: 'Message', t: 'textarea', h: 'Post content' },
    ],
    acts: ['LinkedIn publishing', 'Content amplification'],
  },
  {
    id: 'action-youtube',
    label: 'YouTube',
    icon: 'youtube',
    category: 'Social Media',
    bg: 'rgba(255,0,0,0.18)',
    dot: '#ff0000',
    badge: 'VIDEO',
    bc: 'rgba(255,0,0,0.12)',
    btc: '#ff0000',
    must: false,
    title: 'YouTube Video Upload',
    sub: 'Upload videos to YouTube',
    configs: [
      { l: 'Access Token', t: 'password', h: 'YouTube API token' },
      { l: 'Video Title', t: 'text', h: 'Video title' },
      { l: 'Video Description', t: 'textarea', h: 'Video description' },
      { l: 'Video File', t: 'text', h: 'Path to video file' },
      { l: 'Privacy', t: 'select', o: ['public', 'private', 'unlisted'], h: 'Video privacy' },
    ],
    acts: ['Video uploading', 'Content creation'],
  },
  {
    id: 'action-facebook',
    label: 'Facebook',
    icon: 'facebook',
    category: 'Social Media',
    bg: 'rgba(24,119,242,0.18)',
    dot: '#1877f2',
    badge: 'SOCIAL',
    bc: 'rgba(24,119,242,0.12)',
    btc: '#1877f2',
    must: false,
    title: 'Facebook Post',
    sub: 'Post to Facebook pages',
    configs: [
      { l: 'Access Token', t: 'password', h: 'Facebook page token' },
      { l: 'Page ID', t: 'text', h: 'Facebook page ID' },
      { l: 'Message', t: 'textarea', h: 'Post message' },
      { l: 'Link', t: 'text', h: 'Link to share' },
    ],
    acts: ['Social posting', 'Content sharing'],
  },
  {
    id: 'calendar-google',
    label: 'Google Calendar',
    icon: 'gcalendar',
    category: 'Productivity',
    bg: 'rgba(66,133,244,0.18)',
    dot: '#4285f4',
    badge: 'CALENDAR',
    bc: 'rgba(66,133,244,0.12)',
    btc: '#4285f4',
    must: false,
    title: 'Google Calendar',
    sub: 'Manage Google Calendar events',
    configs: [
      { l: 'Calendar ID', t: 'text', h: 'Calendar ID' },
      { l: 'Event Title', t: 'text', h: 'Event title' },
      { l: 'Start Time', t: 'text', h: 'Event start time' },
      { l: 'End Time', t: 'text', h: 'Event end time' },
    ],
    acts: ['Event creation', 'Calendar management'],
  },
  {
    id: 'data-google-sheets',
    label: 'Google Sheets',
    icon: 'sheets',
    category: 'Data & Storage',
    bg: 'rgba(52,168,83,0.18)',
    dot: '#34a853',
    badge: 'SHEET',
    bc: 'rgba(52,168,83,0.12)',
    btc: '#34a853',
    must: false,
    title: 'Google Sheets',
    sub: 'Read and write spreadsheet rows',
    configs: [
      { l: 'Spreadsheet ID', t: 'text', h: 'Google Sheets id' },
      { l: 'Sheet Name', t: 'text', h: 'Sheet tab name' },
      { l: 'Operation', t: 'select', o: ['read', 'append', 'update'] },
      { l: 'Values', t: 'textarea', h: 'JSON array values' },
    ],
    acts: ['Spreadsheet access', 'Row insertion', 'Data sync'],
  },
  {
    id: 'data-gmail',
    label: 'Gmail',
    icon: 'gmail',
    category: 'Data & Storage',
    bg: 'rgba(220,68,54,0.18)',
    dot: '#d14836',
    badge: 'EMAIL',
    bc: 'rgba(220,68,54,0.12)',
    btc: '#d14836',
    must: false,
    title: 'Gmail Integration',
    sub: 'Read and send Gmail messages',
    configs: [
      { l: 'Gmail Address', t: 'text', h: 'Gmail address' },
      { l: 'Operation', t: 'select', o: ['read', 'send', 'search'] },
      { l: 'Query', t: 'text', h: 'Search query for emails' },
      { l: 'Max Results', t: 'number', h: 'Maximum emails to retrieve' },
    ],
    acts: [
      'Email reading',
      'Message sending',
      'Attachment handling',
      'Label management',
      'Drafts',
      'Attachments',
      'Batch operations',
      'Thread management',
      'Filters',
      'API calls',
    ],
  },
  {
    id: 'trigger-gmail',
    label: 'Gmail Trigger',
    icon: 'gmail',
    category: 'Triggers',
    bg: 'rgba(220,68,54,0.18)',
    dot: '#d14836',
    badge: 'ENTRY',
    bc: 'rgba(220,68,54,0.12)',
    btc: '#d14836',
    must: false,
    title: 'Gmail Trigger',
    sub: 'Fire workflows when new Gmail messages arrive',
    configs: [
      { l: 'Gmail Address', t: 'text', h: 'Gmail address to monitor' },
      { l: 'Search Query', t: 'text', h: 'Gmail search query' },
      { l: 'Poll Interval', t: 'number', h: 'Minutes between checks' },
    ],
    acts: [
      'Email monitoring',
      'Message parsing',
      'Attachment handling',
      'Label management',
      'Filters',
      'API calls',
    ],
  },
  {
    id: 'action-slack',
    label: 'Slack Message',
    icon: 'slack',
    category: 'Actions',
    bg: 'rgba(74,21,122,0.18)',
    dot: '#4f46e5',
    badge: 'CHAT',
    bc: 'rgba(74,21,122,0.12)',
    btc: '#4f46e5',
    must: false,
    title: 'Slack Message',
    sub: 'Send messages to Slack channels',
    configs: [
      { l: 'Webhook URL', t: 'password', h: 'Slack incoming webhook URL' },
      { l: 'Channel', t: 'text', h: 'Slack channel name or ID' },
      { l: 'Message', t: 'textarea', h: 'Message text' },
      { l: 'Username', t: 'text', h: 'Bot username' },
      { l: 'Icon Emoji', t: 'text', h: 'Emoji icon' },
    ],
    acts: ['Team messaging', 'Notifications', 'Alerts'],
  },
  {
    id: 'action-sendgrid',
    label: 'SendGrid Email',
    icon: 'sendgrid',
    category: 'Actions',
    bg: 'rgba(3,169,244,0.18)',
    dot: '#03a9f4',
    badge: 'EMAIL',
    bc: 'rgba(3,169,244,0.12)',
    btc: '#03a9f4',
    must: false,
    title: 'SendGrid Email',
    sub: 'Send email via SendGrid',
    configs: [
      { l: 'API Key', t: 'password', h: 'SendGrid API key' },
      { l: 'From', t: 'text', h: 'Sender email address' },
      { l: 'To', t: 'text', h: 'Recipient email addresses' },
      { l: 'Subject', t: 'text', h: 'Email subject' },
      { l: 'Content', t: 'textarea', h: 'Email body content' },
      { l: 'Category', t: 'text', h: 'SendGrid category for analytics' },
    ],
    acts: ['Transactional email', 'Marketing delivery', 'Notification'],
  },
  {
    id: 'action-twilio-sms',
    label: 'Twilio SMS',
    icon: 'message',
    category: 'Actions',
    bg: 'rgba(37,99,235,0.18)',
    dot: '#2563eb',
    badge: 'SMS',
    bc: 'rgba(37,99,235,0.12)',
    btc: '#2563eb',
    must: false,
    title: 'Twilio SMS',
    sub: 'Send SMS messages via Twilio',
    configs: [
      { l: 'Account SID', t: 'text', h: 'Twilio account SID' },
      { l: 'Auth Token', t: 'password', h: 'Twilio auth token' },
      { l: 'From', t: 'text', h: 'Sender phone number' },
      { l: 'To', t: 'text', h: 'Recipient phone number' },
      { l: 'Message', t: 'textarea', h: 'SMS text message' },
    ],
    acts: ['SMS delivery', 'Notifications', 'Alerts'],
  },
  {
    id: 'action-twilio-call',
    label: 'Twilio Voice',
    icon: 'phone',
    category: 'Actions',
    bg: 'rgba(20,184,166,0.18)',
    dot: '#14b8a6',
    badge: 'VOICE',
    bc: 'rgba(20,184,166,0.12)',
    btc: '#14b8a6',
    must: false,
    title: 'Twilio Voice Call',
    sub: 'Place voice calls through Twilio',
    configs: [
      { l: 'Account SID', t: 'text', h: 'Twilio account SID' },
      { l: 'Auth Token', t: 'password', h: 'Twilio auth token' },
      { l: 'From', t: 'text', h: 'Caller phone number' },
      { l: 'To', t: 'text', h: 'Recipient phone number' },
      { l: 'Twiml URL', t: 'text', h: 'URL for TwiML instructions' },
    ],
    acts: ['Voice calling', 'Automated calls', 'Telephony'],
  },
  {
    id: 'action-stripe',
    label: 'Stripe Payment',
    icon: 'credit-card',
    category: 'Actions',
    bg: 'rgba(88,101,242,0.18)',
    dot: '#5865f2',
    badge: 'PAY',
    bc: 'rgba(88,101,242,0.12)',
    btc: '#5865f2',
    must: false,
    title: 'Stripe Payment',
    sub: 'Create charges and manage payments',
    configs: [
      { l: 'Secret Key', t: 'password', h: 'Stripe secret API key' },
      { l: 'Amount', t: 'number', h: 'Amount in smallest currency unit' },
      { l: 'Currency', t: 'text', h: 'Currency code (e.g. USD)' },
      { l: 'Customer ID', t: 'text', h: 'Stripe customer identifier' },
      { l: 'Description', t: 'text', h: 'Payment description' },
    ],
    acts: ['Payment collection', 'Billing', 'Subscriptions'],
  },
  {
    id: 'tool-serpapi-search',
    label: 'Web Search',
    icon: 'search',
    category: 'Tools',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'SEARCH',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'SerpAPI Web Search',
    sub: 'Search the web using SerpAPI',
    configs: [
      { l: 'Query', t: 'text', h: 'Search query' },
      { l: 'API Key', t: 'password', h: 'SerpAPI key' },
      { l: 'Engine', t: 'select', o: ['google', 'bing', 'duckduckgo'], h: 'Search engine' },
      { l: 'Result Count', t: 'number', h: 'Number of results' },
    ],
    acts: ['Knowledge retrieval', 'Search aggregation', 'Research'],
  },
  {
    id: 'tool-wikipedia',
    label: 'Wikipedia Lookup',
    icon: 'globe',
    category: 'Tools',
    bg: 'rgba(37,99,235,0.18)',
    dot: '#2563eb',
    badge: 'WIKI',
    bc: 'rgba(37,99,235,0.12)',
    btc: '#2563eb',
    must: false,
    title: 'Wikipedia Lookup',
    sub: 'Fetch topic summaries from Wikipedia',
    configs: [{ l: 'Query', t: 'text', h: 'Topic to search' }],
    acts: ['Knowledge retrieval', 'Research', 'Reference'],
  },
  {
    id: 'tool-arxiv',
    label: 'ArXiv Search',
    icon: 'search',
    category: 'Tools',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'RESEARCH',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'ArXiv Search',
    sub: 'Search academic papers on ArXiv',
    configs: [
      { l: 'Query', t: 'text', h: 'Search terms' },
      { l: 'Max Results', t: 'number', h: 'Maximum papers to retrieve' },
    ],
    acts: ['Academic research', 'Paper lookup', 'Literature review'],
  },
  {
    id: 'tool-pubmed',
    label: 'PubMed Search',
    icon: 'search',
    category: 'Tools',
    bg: 'rgba(16,185,129,0.18)',
    dot: '#10b981',
    badge: 'RESEARCH',
    bc: 'rgba(16,185,129,0.12)',
    btc: '#10b981',
    must: false,
    title: 'PubMed Search',
    sub: 'Query PubMed for biomedical papers',
    configs: [
      { l: 'Query', t: 'text', h: 'Search terms' },
      { l: 'Max Results', t: 'number', h: 'Maximum papers to retrieve' },
    ],
    acts: ['Biomedical research', 'Literature search', 'Medical discovery'],
  },
  {
    id: 'tool-weather',
    label: 'Weather Lookup',
    icon: 'cloud',
    category: 'Tools',
    bg: 'rgba(14,165,233,0.18)',
    dot: '#0ea5e9',
    badge: 'WEATHER',
    bc: 'rgba(14,165,233,0.12)',
    btc: '#0ea5e9',
    must: false,
    title: 'Weather Information',
    sub: 'Get current weather data for a location',
    configs: [
      { l: 'Location', t: 'text', h: 'City or coordinates' },
      { l: 'Units', t: 'select', o: ['metric', 'imperial'], h: 'Temperature units' },
      { l: 'API Key', t: 'password', h: 'OpenWeather API key' },
    ],
    acts: ['Weather lookup', 'Forecast retrieval', 'Climate data'],
  },
  {
    id: 'tool-stock-price',
    label: 'Stock Price',
    icon: 'trending-up',
    category: 'Tools',
    bg: 'rgba(234,179,8,0.18)',
    dot: '#eab308',
    badge: 'MARKET',
    bc: 'rgba(234,179,8,0.12)',
    btc: '#eab308',
    must: false,
    title: 'Stock Price Lookup',
    sub: 'Fetch real-time stock prices',
    configs: [
      { l: 'Symbol', t: 'text', h: 'Stock ticker symbol' },
      { l: 'API Key', t: 'password', h: 'Alpha Vantage API key' },
    ],
    acts: ['Market data', 'Finance lookup', 'Ticker data'],
  },
  {
    id: 'tool-currency-exchange',
    label: 'Currency Conversion',
    icon: 'dollar-sign',
    category: 'Tools',
    bg: 'rgba(34,197,94,0.18)',
    dot: '#22c55e',
    badge: 'CURRENCY',
    bc: 'rgba(34,197,94,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'Currency Conversion',
    sub: 'Convert currency values between countries',
    configs: [
      { l: 'From', t: 'text', h: 'Source currency code' },
      { l: 'To', t: 'text', h: 'Target currency code' },
      { l: 'Amount', t: 'number', h: 'Amount to convert' },
      { l: 'API Key', t: 'password', h: 'Exchange rate API key' },
    ],
    acts: ['Currency lookup', 'Conversion', 'Financial operations'],
  },
  {
    id: 'tool-translation',
    label: 'Translation',
    icon: 'globe',
    category: 'Tools',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'LANG',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Text Translation',
    sub: 'Translate text between languages',
    configs: [
      { l: 'Source Language', t: 'text', h: 'Source language code' },
      { l: 'Target Language', t: 'text', h: 'Target language code' },
      { l: 'Text', t: 'textarea', h: 'Text to translate' },
      { l: 'API Key', t: 'password', h: 'Google Translate / LibreTranslate API key' },
    ],
    acts: ['Translation', 'Localization', 'Language processing'],
  },
  {
    id: 'tool-text-summarizer',
    label: 'Text Summarizer',
    icon: 'file-text',
    category: 'Tools',
    bg: 'rgba(14,165,233,0.18)',
    dot: '#0ea5e9',
    badge: 'SUMMARIZE',
    bc: 'rgba(14,165,233,0.12)',
    btc: '#0ea5e9',
    must: false,
    title: 'Text Summarizer',
    sub: 'Generate a summary for long text',
    configs: [
      { l: 'Text', t: 'textarea', h: 'Text to summarize' },
      { l: 'Max Length', t: 'number', h: 'Maximum summary length' },
    ],
    acts: ['Summarization', 'Abstractive summary', 'Text review'],
  },
  {
    id: 'tool-sentiment-analysis',
    label: 'Sentiment Analysis',
    icon: 'smile',
    category: 'Tools',
    bg: 'rgba(249,115,22,0.18)',
    dot: '#f97316',
    badge: 'SENTIMENT',
    bc: 'rgba(249,115,22,0.12)',
    btc: '#f97316',
    must: false,
    title: 'Sentiment Analysis',
    sub: 'Classify text sentiment',
    configs: [
      { l: 'Text', t: 'textarea', h: 'Text to analyze' },
      { l: 'Language', t: 'text', h: 'Language code' },
    ],
    acts: ['Sentiment scoring', 'Opinion mining', 'Feedback analysis'],
  },
  {
    id: 'tool-image-generator',
    label: 'Image Generator',
    icon: 'image',
    category: 'Tools',
    bg: 'rgba(236,72,153,0.18)',
    dot: '#ec4899',
    badge: 'IMAGE',
    bc: 'rgba(236,72,153,0.12)',
    btc: '#ec4899',
    must: false,
    title: 'Image Generator',
    sub: 'Generate images from prompts',
    configs: [
      { l: 'Prompt', t: 'textarea', h: 'Image prompt' },
      { l: 'Model', t: 'text', h: 'Image generation model' },
      { l: 'Width', t: 'number', h: 'Image width in pixels' },
      { l: 'Height', t: 'number', h: 'Image height in pixels' },
      { l: 'API Key', t: 'password', h: 'Stability or image API key' },
    ],
    acts: ['Image generation', 'Visual creation', 'Asset production'],
  },
  {
    id: 'tool-code-executor',
    label: 'Code Executor',
    icon: 'cpu',
    category: 'Tools',
    bg: 'rgba(14,165,233,0.18)',
    dot: '#0ea5e9',
    badge: 'CODE',
    bc: 'rgba(14,165,233,0.12)',
    btc: '#0ea5e9',
    must: false,
    title: 'Code Executor',
    sub: 'Run custom code snippets safely',
    configs: [
      { l: 'Language', t: 'select', o: ['javascript', 'python'], h: 'Execution language' },
      { l: 'Code', t: 'textarea', h: 'Code to execute' },
      { l: 'Input Data', t: 'textarea', h: 'JSON input data' },
    ],
    acts: ['Code execution', 'Scripting', 'Transformation'],
  },
  {
    id: 'tool-database-query',
    label: 'Database Query',
    icon: 'database',
    category: 'Tools',
    bg: 'rgba(10,132,255,0.18)',
    dot: '#0a84ff',
    badge: 'DB',
    bc: 'rgba(10,132,255,0.12)',
    btc: '#0a84ff',
    must: false,
    title: 'Database Query',
    sub: 'Run SQL queries against a database',
    configs: [
      { l: 'Connection String', t: 'text', h: 'Database connection string' },
      { l: 'Query', t: 'textarea', h: 'SQL query to execute' },
      { l: 'Timeout', t: 'number', h: 'Query timeout seconds' },
    ],
    acts: ['SQL execution', 'Data extraction', 'Reporting'],
  },
  {
    id: 'tool-email-parser',
    label: 'Email Parser',
    icon: 'mail',
    category: 'Tools',
    bg: 'rgba(148,163,184,0.18)',
    dot: '#94a3b8',
    badge: 'PARSER',
    bc: 'rgba(148,163,184,0.12)',
    btc: '#94a3b8',
    must: false,
    title: 'Email Parser',
    sub: 'Parse email content into structured fields',
    configs: [{ l: 'Email Content', t: 'textarea', h: 'Raw email text' }],
    acts: ['Email parsing', 'Metadata extraction', 'Automation'],
  },
  {
    id: 'tool-json-parser',
    label: 'JSON Parser',
    icon: 'file-text',
    category: 'Tools',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'JSON',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'JSON Parser',
    sub: 'Parse JSON strings into objects',
    configs: [{ l: 'JSON String', t: 'textarea', h: 'JSON text to parse' }],
    acts: ['JSON parsing', 'Data validation', 'Data transformation'],
  },
  {
    id: 'tool-regex-matcher',
    label: 'Regex Matcher',
    icon: 'search',
    category: 'Tools',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'REGEX',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Regex Matcher',
    sub: 'Match text with regular expressions',
    configs: [
      { l: 'Text', t: 'textarea', h: 'Text to search' },
      { l: 'Pattern', t: 'text', h: 'Regex pattern' },
      { l: 'Flags', t: 'text', h: 'Regex flags' },
    ],
    acts: ['Pattern matching', 'Text extraction', 'Validation'],
  },
  {
    id: 'tool-date-manipulator',
    label: 'Date Manipulator',
    icon: 'clock',
    category: 'Tools',
    bg: 'rgba(245,158,11,0.18)',
    dot: '#f59e0b',
    badge: 'DATE',
    bc: 'rgba(245,158,11,0.12)',
    btc: '#f59e0b',
    must: false,
    title: 'Date Manipulator',
    sub: 'Parse and manipulate date values',
    configs: [
      { l: 'Date String', t: 'text', h: 'Date text to parse' },
      { l: 'Operation', t: 'select', o: ['parse', 'add'], h: 'Date operation' },
      { l: 'Amount', t: 'number', h: 'Amount to add' },
      { l: 'Unit', t: 'select', o: ['days', 'hours', 'minutes', 'seconds'], h: 'Time unit' },
      { l: 'Format', t: 'select', o: ['ISO', 'locale', 'date'], h: 'Output format' },
    ],
    acts: ['Date formatting', 'Time calculation', 'Temporal logic'],
  },
  {
    id: 'agent-reason',
    label: 'Agent Reason',
    icon: 'activity',
    category: 'Agent Orchestration',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'REASON',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'Reasoning Node',
    sub: 'Generate reasoning for the next action',
    configs: [
      { l: 'Task', t: 'text', h: 'Problem or task description' },
      { l: 'Context', t: 'textarea', h: 'Current context or history' },
    ],
    acts: ['Agent reasoning', 'Decision making', 'Next step planning'],
  },
  {
    id: 'agent-act',
    label: 'Agent Act',
    icon: 'zap',
    category: 'Agent Orchestration',
    bg: 'rgba(16,185,129,0.18)',
    dot: '#10b981',
    badge: 'ACTION',
    bc: 'rgba(16,185,129,0.12)',
    btc: '#10b981',
    must: false,
    title: 'Action Node',
    sub: 'Execute the chosen agent action',
    configs: [
      { l: 'Action', t: 'text', h: 'Action identifier or description' },
      { l: 'Parameters', t: 'textarea', h: 'Action parameters as JSON' },
    ],
    acts: ['Agent action', 'Task execution', 'Tool orchestration'],
  },
  {
    id: 'agent-plan',
    label: 'Agent Plan',
    icon: 'layers',
    category: 'Agent Orchestration',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'PLAN',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Planning Node',
    sub: 'Create a step-by-step execution plan',
    configs: [
      { l: 'Goal', t: 'text', h: 'Goal to achieve' },
      { l: 'Constraints', t: 'textarea', h: 'Constraints or business rules' },
    ],
    acts: ['Planning', 'Strategy', 'Task breakdown'],
  },
  {
    id: 'agent-reflect',
    label: 'Agent Reflect',
    icon: 'rotate-ccw',
    category: 'Agent Orchestration',
    bg: 'rgba(245,158,11,0.18)',
    dot: '#f59e0b',
    badge: 'REFLECT',
    bc: 'rgba(245,158,11,0.12)',
    btc: '#f59e0b',
    must: false,
    title: 'Reflection Node',
    sub: 'Analyze past actions and improve execution',
    configs: [
      { l: 'Performance', t: 'textarea', h: 'Execution performance metrics' },
      { l: 'History', t: 'textarea', h: 'Recent execution history' },
      { l: 'Confidence', t: 'number', h: 'Current confidence score' },
    ],
    acts: ['Self-reflection', 'Feedback loop', 'Adaptive improvement'],
  },
  {
    id: 'agent-looping',
    label: 'Looping Agent',
    icon: 'repeat',
    category: 'Agent Orchestration',
    bg: 'rgba(139,69,19,0.18)',
    dot: '#8b4513',
    badge: 'LOOP',
    bc: 'rgba(139,69,19,0.12)',
    btc: '#8b4513',
    must: false,
    title: 'Looping Agent Node',
    sub: 'Iterative agent that repeats tasks until conditions are met',
    configs: [
      { l: 'Max Iterations', t: 'number', h: 'Maximum number of loop iterations' },
      { l: 'Loop Condition', t: 'textarea', h: 'JavaScript condition to continue looping' },
      { l: 'Iteration Delay', t: 'number', h: 'Delay between iterations (ms)' },
      {
        l: 'Exit Strategy',
        t: 'select',
        o: ['condition', 'timeout', 'manual'],
        h: 'How to exit the loop',
        required: true,
      },
      {
        l: 'State Accumulation',
        t: 'select',
        o: ['merge', 'append', 'replace'],
        h: 'How to handle state between iterations',
        required: true,
      },
    ],
    acts: ['Iterative processing', 'Conditional loops', 'State accumulation'],
  },
  {
    id: 'agent-react',
    label: 'ReAct Agent',
    icon: 'brain',
    category: 'Agent Orchestration',
    bg: 'rgba(147,51,234,0.18)',
    dot: '#9333ea',
    badge: 'REACT',
    bc: 'rgba(147,51,234,0.12)',
    btc: '#9333ea',
    must: false,
    title: 'Reasoning + Acting Agent',
    sub: 'Agent that alternates between reasoning and taking actions',
    configs: [
      {
        l: 'Reasoning Model',
        t: 'select',
        o: ['gpt-4', 'claude-3', 'gemini-pro'],
        h: 'AI model for reasoning',
        required: true,
      },
      {
        l: 'Action Model',
        t: 'select',
        o: ['gpt-4', 'claude-3', 'gemini-pro'],
        h: 'AI model for action selection',
        required: true,
      },
      { l: 'Max Reasoning Steps', t: 'number', h: 'Maximum reasoning iterations' },
      { l: 'Action Threshold', t: 'number', h: 'Confidence threshold for actions' },
      { l: 'Reasoning Prompt', t: 'textarea', h: 'Custom reasoning instructions' },
      { l: 'Action Prompt', t: 'textarea', h: 'Custom action selection instructions' },
    ],
    acts: ['Reasoning loops', 'Action selection', 'Iterative problem solving'],
  },
  {
    id: 'agent-reasoning',
    label: 'Reasoning Agent',
    icon: 'lightbulb',
    category: 'Agent Orchestration',
    bg: 'rgba(34,197,94,0.18)',
    dot: '#22c55e',
    badge: 'REASON',
    bc: 'rgba(34,197,94,0.12)',
    btc: '#22c55e',
    must: false,
    title: 'Pure Reasoning Agent',
    sub: 'Agent focused on deep reasoning and analysis',
    configs: [
      {
        l: 'Reasoning Depth',
        t: 'select',
        o: ['shallow', 'medium', 'deep', 'extreme'],
        h: 'Depth of reasoning analysis',
        required: true,
      },
      {
        l: 'Analysis Framework',
        t: 'select',
        o: ['logical', 'systematic', 'creative', 'critical'],
        h: 'Reasoning methodology',
        required: true,
      },
      { l: 'Evidence Weight', t: 'number', h: 'How much to weight evidence vs intuition' },
      {
        l: 'Uncertainty Handling',
        t: 'select',
        o: ['conservative', 'balanced', 'optimistic'],
        h: 'How to handle uncertainty',
        required: true,
      },
      { l: 'Reasoning Prompt', t: 'textarea', h: 'Custom reasoning instructions' },
      {
        l: 'Output Format',
        t: 'select',
        o: ['structured', 'narrative', 'bullet-points'],
        h: 'Reasoning output format',
        required: true,
      },
    ],
    acts: ['Deep analysis', 'Logical reasoning', 'Problem decomposition'],
  },
  {
    id: 'agent-planning',
    label: 'Planning Agent',
    icon: 'map',
    category: 'Agent Orchestration',
    bg: 'rgba(59,130,246,0.18)',
    dot: '#3b82f6',
    badge: 'PLAN',
    bc: 'rgba(59,130,246,0.12)',
    btc: '#3b82f6',
    must: false,
    title: 'Plan-then-Execute Agent',
    sub: 'Agent that creates detailed plans before execution',
    configs: [
      {
        l: 'Planning Horizon',
        t: 'select',
        o: ['short', 'medium', 'long', 'strategic'],
        h: 'Time horizon for planning',
        required: true,
      },
      {
        l: 'Risk Assessment',
        t: 'select',
        o: ['low', 'medium', 'high', 'extreme'],
        h: 'Risk consideration level',
        required: true,
      },
      { l: 'Resource Constraints', t: 'textarea', h: 'Available resources and limitations' },
      { l: 'Success Criteria', t: 'textarea', h: 'What constitutes successful completion' },
      { l: 'Contingency Plans', t: 'number', h: 'Number of backup plans to generate' },
      { l: 'Planning Prompt', t: 'textarea', h: 'Custom planning instructions' },
    ],
    acts: ['Strategic planning', 'Risk assessment', 'Resource optimization'],
  },
  {
    id: 'agent-multi',
    label: 'Multi-Agent System',
    icon: 'users',
    category: 'Agent Orchestration',
    bg: 'rgba(236,72,153,0.18)',
    dot: '#ec4899',
    badge: 'MULTI',
    bc: 'rgba(236,72,153,0.12)',
    btc: '#ec4899',
    must: false,
    title: 'Multi-Agent Coordinator',
    sub: 'Coordinates multiple specialized agents',
    configs: [
      { l: 'Agent Roles', t: 'textarea', h: 'Roles and responsibilities of each agent' },
      {
        l: 'Communication Protocol',
        t: 'select',
        o: ['hierarchical', 'peer-to-peer', 'market-based'],
        h: 'How agents communicate',
        required: true,
      },
      {
        l: 'Conflict Resolution',
        t: 'select',
        o: ['voting', 'priority', 'negotiation'],
        h: 'How to resolve conflicts',
        required: true,
      },
      {
        l: 'Shared Memory',
        t: 'select',
        o: ['global', 'selective', 'none'],
        h: 'Memory sharing between agents',
        required: true,
      },
      { l: 'Max Agents', t: 'number', h: 'Maximum number of concurrent agents' },
      { l: 'Coordination Prompt', t: 'textarea', h: 'Instructions for agent coordination' },
    ],
    acts: ['Agent coordination', 'Task delegation', 'Collaborative problem solving'],
  },
  {
    id: 'agent-tool-using',
    label: 'Tool-Using Agent',
    icon: 'wrench',
    category: 'Agent Orchestration',
    bg: 'rgba(245,101,101,0.18)',
    dot: '#f56565',
    badge: 'TOOLS',
    bc: 'rgba(245,101,101,0.12)',
    btc: '#f56565',
    must: false,
    title: 'Tool-Focused Agent',
    sub: 'Agent specialized in using external tools and APIs',
    configs: [
      {
        l: 'Tool Discovery',
        t: 'select',
        o: ['manual', 'automatic', 'hybrid'],
        h: 'How tools are discovered',
        required: true,
      },
      {
        l: 'Tool Selection Strategy',
        t: 'select',
        o: ['efficiency', 'reliability', 'cost'],
        h: 'Criteria for tool selection',
        required: true,
      },
      {
        l: 'Fallback Behavior',
        t: 'select',
        o: ['retry', 'alternative', 'fail'],
        h: 'What to do when tools fail',
        required: true,
      },
      { l: 'Tool Usage Limits', t: 'textarea', h: 'Rate limits and usage constraints' },
      { l: 'Tool Prompt', t: 'textarea', h: 'Instructions for tool usage' },
      {
        l: 'Result Validation',
        t: 'select',
        o: ['strict', 'lenient', 'none'],
        h: 'How to validate tool results',
        required: true,
      },
    ],
    acts: ['Tool orchestration', 'API integration', 'External service usage'],
  },
  {
    id: 'agent-memory',
    label: 'Memory Agent',
    icon: 'database',
    category: 'Agent Orchestration',
    bg: 'rgba(251,146,60,0.18)',
    dot: '#fb923c',
    badge: 'MEMORY',
    bc: 'rgba(251,146,60,0.12)',
    btc: '#fb923c',
    must: false,
    title: 'Memory-Enhanced Agent',
    sub: 'Agent with advanced memory and context management',
    configs: [
      {
        l: 'Memory Type',
        t: 'select',
        o: ['episodic', 'semantic', 'procedural', 'working'],
        h: 'Type of memory to use',
        required: true,
      },
      { l: 'Memory Capacity', t: 'number', h: 'Maximum memory items to retain' },
      {
        l: 'Retrieval Strategy',
        t: 'select',
        o: ['recent', 'relevant', 'frequent', 'important'],
        h: 'How to retrieve memories',
        required: true,
      },
      {
        l: 'Forgetting Policy',
        t: 'select',
        o: ['lru', 'importance', 'time-based', 'manual'],
        h: 'When to forget memories',
        required: true,
      },
      { l: 'Context Window', t: 'number', h: 'Size of context window for memory' },
      { l: 'Memory Prompt', t: 'textarea', h: 'Instructions for memory usage' },
    ],
    acts: ['Context retention', 'Experience learning', 'Adaptive behavior'],
  },
  {
    id: 'denbegaye-agent',
    label: 'Denbegaye Autonomous Agent',
    icon: 'agent-multi',
    category: 'Agent Orchestration',
    bg: 'rgba(244,63,94,0.18)',
    dot: '#f43f5e',
    badge: 'AUTONOMOUS',
    bc: 'rgba(244,63,94,0.12)',
    btc: '#f43f5e',
    must: false,
    title: 'Autonomous Denbegaye Agent',
    sub: 'Self-governing agent with LLM integration, tool calling, and memory',
    configs: [
      {
        l: 'LLM Provider',
        t: 'select',
        o: ['gemini', 'openai', 'anthropic', 'deepseek', 'groq'],
        h: 'Select LLM provider',
        required: true,
      },
      {
        l: 'Model',
        t: 'select',
        o: [
          'gemini-2.5-flash',
          'gemini-2.0-pro',
          'gemini-1.5-pro',
          'gpt-4o',
          'gpt-4o-mini',
          'claude-3-5-sonnet-20241022',
          'deepseek-v4-pro',
          'groq-mixtral',
        ],
        d: 'gemini-2.5-flash',
        h: 'LLM model to use',
        required: true,
        condition: (configValues: Record<string, any>) => !!configValues['LLM Provider'],
      },
      { l: 'API Key', t: 'password', h: 'API key for the selected provider', required: true },
      { l: 'System Prompt', t: 'textarea', h: 'System instructions for the agent', required: true },
      { l: 'Temperature', t: 'number', h: 'Creativity level (0-2)' },
      { l: 'Max Tokens', t: 'number', h: 'Maximum response length' },
      {
        l: 'Enable Tool Calling',
        t: 'select',
        o: ['yes', 'no'],
        h: 'Allow the agent to call external tools',
        required: true,
      },
      {
        l: 'Tools',
        t: 'textarea',
        h: 'Comma-separated list of available tools',
        condition: (configValues: Record<string, any>) =>
          configValues['Enable Tool Calling'] === 'yes',
      },
      {
        l: 'Enable Memory',
        t: 'select',
        o: ['yes', 'no'],
        h: 'Enable memory system for context retention',
        required: true,
      },
      {
        l: 'Memory Type',
        t: 'select',
        o: ['episodic', 'semantic', 'working'],
        h: 'Type of memory to use',
        condition: (configValues: Record<string, any>) => configValues['Enable Memory'] === 'yes',
      },
      { l: 'Max Iterations', t: 'number', h: 'Maximum reasoning iterations (default: 10)' },
      {
        l: 'Reasoning Type',
        t: 'select',
        o: ['step-by-step', 'chain-of-thought', 'tree-of-thought'],
        h: 'Reasoning strategy',
      },
      {
        l: 'Output Format',
        t: 'select',
        o: ['text', 'json', 'structured'],
        h: 'Format for agent output',
      },
      { l: 'Input Text', t: 'textarea', h: 'Input for the agent to process', required: true },
    ],
    acts: [
      'Autonomous reasoning',
      'Tool orchestration',
      'Multi-step planning',
      'Memory management',
      'Dynamic decision making',
      'Self-reflection',
      'Adaptive learning',
    ],
  },
  {
    id: 'react-agent',
    label: 'ReAct Agent',
    icon: 'brain',
    category: 'ai',
    bg: 'rgba(147,51,234,0.18)',
    dot: '#9333ea',
    badge: 'REACT',
    bc: 'rgba(147,51,234,0.12)',
    btc: '#9333ea',
    must: false,
    title: 'ReAct Agent',
    sub: 'Reasoning + Acting loop using LLM and workflow tools',
    configs: [
      { l: 'API Key', t: 'password', h: 'API key for the selected LLM provider', required: true },
      {
        l: 'LLM Provider',
        t: 'select',
        o: ['gemini', 'openai', 'anthropic', 'deepseek', 'groq'],
        h: 'Select LLM provider',
        required: true,
        d: 'openai',
      },
      {
        l: 'Model',
        t: 'select',
        o: [],
        h: 'LLM model name (choose from provider-specific options)',
        required: true,
      },
      { l: 'System Prompt', t: 'textarea', h: 'System instructions for the agent', required: true },
      {
        l: 'Max Iterations',
        t: 'number',
        d: 5,
        h: 'Maximum ReAct iterations (server capped at 10)',
      },
      { l: 'Allowed Tools', t: 'multiselect', o: [], h: 'Select allowed tool node types' },
    ],
    acts: ['ReAct reasoning', 'Tool orchestration', 'Iterative problem solving'],
  },
  {
    id: 'memory-store',
    label: 'Store memory',
    icon: 'database',
    category: 'Memory',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'MEMORY',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Store Memory',
    sub: 'Save structured content into long-term semantic memory',
    description: 'Store information into long-term agent memory with vector embedding',
    configs: [
      {
        l: 'Content to store',
        t: 'textarea',
        h: 'Leave empty to use the previous node output',
      },
      {
        l: 'Metadata tags',
        t: 'keyvalue',
        h: 'Optional key-value pairs attached to this memory for filtering',
      },
      {
        l: 'Memory type',
        t: 'select',
        o: ['general', 'fact', 'instruction', 'episode'],
        d: 'general',
        h: 'Choose a semantic category for stored memory',
        required: true,
      },
    ],
    acts: ['Memory storage', 'Semantic persistence', 'Context enrichment'],
  },
  {
    id: 'memory-recall',
    label: 'Recall memory',
    icon: 'database',
    category: 'Memory',
    bg: 'rgba(168,85,247,0.18)',
    dot: '#a855f7',
    badge: 'MEMORY',
    bc: 'rgba(168,85,247,0.12)',
    btc: '#a855f7',
    must: false,
    title: 'Recall Memory',
    sub: 'Retrieve relevant long-term semantic memories',
    description: 'Search long-term agent memory for semantically similar content',
    configs: [
      {
        l: 'Search query',
        t: 'textarea',
        h: 'Leave empty to use the previous node output as the search query',
      },
      {
        l: 'Max results',
        t: 'number',
        d: 5,
        h: 'Maximum number of results',
      },
      {
        l: 'Memory type',
        t: 'select',
        o: ['general', 'fact', 'instruction', 'episode'],
        d: 'general',
        h: 'Choose the memory category to search within',
        required: true,
      },
    ],
    acts: ['Memory retrieval', 'Semantic search', 'Context recall'],
  },
  {
    id: 'human-pause',
    category: 'control',
    label: 'Human approval',
    description:
      'Pause execution and wait for a human to approve or reject before the agent continues',
    configs: [
      {
        l: 'Question for the reviewer',
        t: 'textarea',
        h: 'Describe what the reviewer should check before approving',
        required: true,
      },
      {
        l: 'Response options',
        t: 'tags',
        d: ['Approve', 'Reject'],
        h: 'The choices presented to the reviewer. First option is treated as approval.',
      },
      {
        l: 'Timeout in milliseconds',
        t: 'number',
        d: 300000,
        h: 'How long to wait for approval before timing out. Default is 5 minutes.',
      },
    ],
  },
  // More nodes will be added in subsequent responses...
];

export const sidebarItems: SidebarItem[] = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard },
  { id: 'builder', label: 'Builder', icon: Wrench },
  { id: 'templates', label: 'Templates', icon: Sparkles },
  { id: 'vault', label: 'Credential Vault', icon: Lock },
  { id: 'settings', label: 'Settings', icon: SlidersHorizontal },
];

export const nodeTypes = {
  group: GroupNode,
  'ai-gemini': AINode,
  'ai-openai': AINode,
  'ai-anthropic': AINode,
  'ai-grok': AINode,
  'ai-deepseek': AINode,
  'trigger-webhook': ToolNode,
  'trigger-schedule': ToolNode,
  'trigger-email': ToolNode,
  'trigger-calendar-event': ToolNode,
  'trigger-slack-event': ToolNode,
  'trigger-sms': ToolNode,
  'trigger-form-submission': ToolNode,
  'trigger-website-form': ToolNode,
  'trigger-manual': ToolNode,
  'trigger-chat-input': ToolNode,
  'core-http-request': ToolNode,
  'core-code-js': ToolNode,
  'core-code-python': ToolNode,
  'core-set': ToolNode,
  'logic-if': ToolNode,
  'logic-switch': ToolNode,
  'logic-loop': ToolNode,
  'logic-wait': ToolNode,
  'action-email': ToolNode,
  'action-webhook': ToolNode,
  'action-telegram': ToolNode,
  'action-whatsapp': ToolNode,
  'action-linkedin': ToolNode,
  'action-youtube': ToolNode,
  'action-facebook': ToolNode,
  'action-slack': ToolNode,
  'action-sendgrid': ToolNode,
  'action-twilio-sms': ToolNode,
  'action-twilio-call': ToolNode,
  'action-stripe': ToolNode,
  'calendar-google': ToolNode,
  'data-google-sheets': ToolNode,
  'data-gmail': ToolNode,
  'data-postgres': ToolNode,
  'data-mysql': ToolNode,
  'data-mongodb': ToolNode,
  'data-supabase': ToolNode,
  'tool-serpapi-search': ToolNode,
  'tool-wikipedia': ToolNode,
  'tool-arxiv': ToolNode,
  'tool-pubmed': ToolNode,
  'tool-weather': ToolNode,
  'tool-stock-price': ToolNode,
  'tool-currency-exchange': ToolNode,
  'tool-translation': ToolNode,
  'tool-text-summarizer': ToolNode,
  'tool-sentiment-analysis': ToolNode,
  'tool-image-generator': ToolNode,
  'tool-code-executor': ToolNode,
  'tool-database-query': ToolNode,
  'tool-email-parser': ToolNode,
  'tool-json-parser': ToolNode,
  'tool-regex-matcher': ToolNode,
  'tool-date-manipulator': ToolNode,
  'agent-reason': ToolNode,
  'agent-act': ToolNode,
  'agent-plan': ToolNode,
  'agent-reflect': ToolNode,
  'agent-looping': ToolNode,
  'agent-react': ToolNode,
  'react-agent': ToolNode,
  'agent-reasoning': ToolNode,
  'agent-planning': ToolNode,
  'agent-multi': ToolNode,
  'agent-tool-using': ToolNode,
  'agent-memory': ToolNode,
  'human-pause': ToolNode,
  'denbegaye-agent': DenbegayeAgentNode,
  'trigger-gmail': ToolNode,
};
