export const availableNodeTypes = [
  // AI Nodes
  {
    id: 'ai-google-gemini',
    name: 'Google Gemini',
    description:
      'Advanced AI reasoning using Google Gemini models with comprehensive functionality',
    category: 'ai',
    icon: '🤖',
    color: '#4285F4',
    inputs: [{ id: 'data', label: 'Input Data', type: 'object', required: true }],
    outputs: [
      { id: 'result', label: 'Result', type: 'object' },
      { id: 'usage', label: 'Usage Stats', type: 'object' },
      { id: 'candidates', label: 'All Candidates', type: 'array' },
    ],
    configSchema: {
      action: {
        type: 'select',
        options: [
          'generateText',
          'sendChatMessage',
          'analyzeImage',
          'generateJson',
          'countTokens',
          'createEmbedding',
          'summarizeContent',
          'classifyText',
          'extractStructuredData',
          'translateText',
          'textToSpeech',
          'generateImage',
          'generateVideo',
          'analyzeVideo',
          'analyzeAudio',
          'codeGeneration',
          'codeExecution',
          'functionCalling',
          'groundingWithGoogleSearch',
        ],
        default: 'generateText',
      },
      model: {
        type: 'select',
        options: [
          'gemini-2.5-flash',
          'gemini-1.5-pro',
          'gemini-1.5-flash',
          'gemini-1.5-pro-002',
          'gemini-1.5-flash-002',
          'gemini-2.0-flash-exp',
          'gemini-pro',
          'gemini-pro-vision',
          'imagen-3.0-generate-001',
          'veo-2.0-generate-001',
        ],
        default: 'gemini-2.5-flash',
      },
      temperature: { type: 'number', min: 0, max: 2, default: 0.7 },
      topP: { type: 'number', min: 0, max: 1, required: false },
      topK: { type: 'number', min: 1, max: 100, required: false },
      maxTokens: { type: 'number', min: 1, max: 8192, default: 2048 },
      stopSequences: { type: 'array', required: false },
      candidateCount: { type: 'number', min: 1, max: 8, default: 1 },
      safetySettings: {
        type: 'object',
        properties: {
          harassment: {
            type: 'select',
            options: ['block_none', 'block_few', 'block_some', 'block_most'],
            default: 'block_some',
          },
          hateSpeech: {
            type: 'select',
            options: ['block_none', 'block_few', 'block_some', 'block_most'],
            default: 'block_some',
          },
          sexuallyExplicit: {
            type: 'select',
            options: ['block_none', 'block_few', 'block_some', 'block_most'],
            default: 'block_some',
          },
          dangerousContent: {
            type: 'select',
            options: ['block_none', 'block_few', 'block_some', 'block_most'],
            default: 'block_some',
          },
        },
        required: false,
      },
      systemPrompt: { type: 'textarea', required: false },
      apiKey: { type: 'password', required: true },
      retry: {
        type: 'object',
        properties: {
          maxRetries: { type: 'number', min: 0, max: 10, default: 3 },
          backoffMs: { type: 'number', min: 100, max: 10000, default: 1000 },
        },
        required: false,
      },
      timeout: { type: 'number', min: 1000, max: 300000, default: 30000 },
      logging: {
        type: 'object',
        properties: {
          level: {
            type: 'select',
            options: ['debug', 'info', 'warn', 'error'],
            default: 'info',
          },
          metadata: { type: 'object', required: false },
        },
        required: false,
      },
    },
  },

  // Trigger Nodes
  {
    id: 'trigger-webhook',
    name: 'Webhook Trigger',
    description: 'Triggers workflow execution via HTTP webhook calls',
    category: 'trigger',
    icon: '🔗',
    color: '#FF6B6B',
    inputs: [],
    outputs: [
      { id: 'payload', label: 'Request Payload', type: 'object' },
      { id: 'headers', label: 'Request Headers', type: 'object' },
      { id: 'query', label: 'Query Parameters', type: 'object' },
      { id: 'method', label: 'HTTP Method', type: 'string' },
    ],
    configSchema: {
      path: { type: 'text', default: '/webhook' },
      method: {
        type: 'select',
        options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
        default: 'POST',
      },
      secret: { type: 'password', required: false },
      validateSignature: { type: 'boolean', default: false },
      timeout: { type: 'number', min: 1000, max: 300000, default: 30000 },
    },
  },
  {
    id: 'trigger-email',
    name: 'Email Trigger',
    description: 'Triggers workflow execution when new emails are received',
    category: 'trigger',
    icon: '📧',
    color: '#EA4335',
    inputs: [],
    outputs: [
      { id: 'email', label: 'Email Data', type: 'object' },
      { id: 'subject', label: 'Subject', type: 'string' },
      { id: 'body', label: 'Body', type: 'string' },
      { id: 'sender', label: 'Sender', type: 'string' },
      { id: 'attachments', label: 'Attachments', type: 'array' },
    ],
    configSchema: {
      email: { type: 'email', required: true },
      password: { type: 'password', required: true },
      host: { type: 'text', default: 'imap.gmail.com' },
      port: { type: 'number', default: 993 },
      tls: { type: 'boolean', default: true },
      checkInterval: { type: 'number', min: 1000, max: 3600000, default: 30000 },
      markAsRead: { type: 'boolean', default: true },
      deleteAfterProcessing: { type: 'boolean', default: false },
    },
  },

  // Core Nodes
  {
    id: 'core-http-request',
    name: 'HTTP Request',
    description: 'Make HTTP requests to external APIs and services',
    category: 'core',
    icon: '🌐',
    color: '#00ACC1',
    inputs: [
      { id: 'url', label: 'URL', type: 'string', required: false },
      { id: 'method', label: 'Method', type: 'string', required: false },
      { id: 'headers', label: 'Headers', type: 'object', required: false },
      { id: 'body', label: 'Request Body', type: 'any', required: false },
      { id: 'query', label: 'Query Parameters', type: 'object', required: false },
    ],
    outputs: [
      { id: 'response', label: 'Response', type: 'object' },
      { id: 'data', label: 'Response Data', type: 'any' },
      { id: 'status', label: 'Status Code', type: 'number' },
      { id: 'headers', label: 'Response Headers', type: 'object' },
    ],
    configSchema: {
      method: {
        type: 'select',
        options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
        default: 'GET',
      },
      url: { type: 'url', required: true },
      headers: { type: 'keyvalue', default: {} },
      timeout: { type: 'number', min: 1000, max: 300000, default: 30000 },
      retries: { type: 'number', min: 0, max: 10, default: 0 },
      retryDelay: { type: 'number', min: 100, max: 10000, default: 1000 },
      followRedirects: { type: 'boolean', default: true },
    },
  },

  // Social Media Nodes
  {
    id: 'social-telegram',
    name: 'Telegram Bot',
    description: 'Send messages and interact with Telegram bots',
    category: 'social',
    icon: '📱',
    color: '#0088CC',
    inputs: [
      { id: 'message', label: 'Message', type: 'string', required: true },
      { id: 'chatId', label: 'Chat ID', type: 'string', required: false },
      { id: 'replyToMessageId', label: 'Reply To', type: 'string', required: false },
      { id: 'attachments', label: 'Attachments', type: 'array', required: false },
    ],
    outputs: [
      { id: 'messageId', label: 'Message ID', type: 'string' },
      { id: 'response', label: 'API Response', type: 'object' },
    ],
    configSchema: {
      botToken: { type: 'password', required: true },
      chatId: { type: 'text', required: true },
      parseMode: { type: 'select', options: ['Markdown', 'HTML', 'MarkdownV2'], default: 'HTML' },
      disableWebPagePreview: { type: 'boolean', default: false },
      disableNotification: { type: 'boolean', default: false },
    },
  },
  {
    id: 'social-whatsapp',
    name: 'WhatsApp Business',
    description: 'Send messages via WhatsApp Business API',
    category: 'social',
    icon: '💬',
    color: '#25D366',
    inputs: [
      { id: 'to', label: 'Recipient', type: 'string', required: true },
      { id: 'message', label: 'Message', type: 'string', required: true },
      { id: 'type', label: 'Message Type', type: 'string', required: false },
      { id: 'media', label: 'Media URL', type: 'string', required: false },
    ],
    outputs: [
      { id: 'messageId', label: 'Message ID', type: 'string' },
      { id: 'response', label: 'API Response', type: 'object' },
    ],
    configSchema: {
      accessToken: { type: 'password', required: true },
      phoneNumberId: { type: 'text', required: true },
      apiVersion: { type: 'text', default: 'v18.0' },
      timeout: { type: 'number', min: 1000, max: 300000, default: 30000 },
    },
  },
  {
    id: 'social-linkedin',
    name: 'LinkedIn',
    description: 'Post updates and interact with LinkedIn API',
    category: 'social',
    icon: '💼',
    color: '#0077B5',
    inputs: [
      { id: 'action', label: 'Action', type: 'string', required: true },
      { id: 'pageId', label: 'Page ID', type: 'string', required: false },
      { id: 'content', label: 'Content', type: 'string', required: false },
      { id: 'postId', label: 'Post ID', type: 'string', required: false },
    ],
    outputs: [
      { id: 'postId', label: 'Post ID', type: 'string' },
      { id: 'posts', label: 'Posts', type: 'array' },
      { id: 'response', label: 'API Response', type: 'object' },
    ],
    configSchema: {
      accessToken: { type: 'password', required: true },
      apiVersion: { type: 'text', default: 'v2' },
      timeout: { type: 'number', min: 1000, max: 300000, default: 30000 },
    },
  },
  {
    id: 'social-youtube',
    name: 'YouTube',
    description: 'Interact with YouTube API for videos, channels, and analytics',
    category: 'social',
    icon: '📺',
    color: '#FF0000',
    inputs: [
      { id: 'action', label: 'Action', type: 'string', required: true },
      { id: 'query', label: 'Query', type: 'string', required: false },
      { id: 'videoData', label: 'Video Data', type: 'object', required: false },
      { id: 'channelId', label: 'Channel ID', type: 'string', required: false },
    ],
    outputs: [
      { id: 'results', label: 'Results', type: 'array' },
      { id: 'video', label: 'Video', type: 'object' },
      { id: 'response', label: 'API Response', type: 'object' },
    ],
    configSchema: {
      apiKey: { type: 'password', required: true },
      accessToken: { type: 'password', required: false },
      clientId: { type: 'text', required: false },
      clientSecret: { type: 'password', required: false },
      refreshToken: { type: 'password', required: false },
    },
  },
  {
    id: 'social-facebook',
    name: 'Facebook',
    description: 'Post updates and interact with Facebook API',
    category: 'social',
    icon: '👥',
    color: '#1877F2',
    inputs: [
      { id: 'action', label: 'Action', type: 'string', required: true },
      { id: 'pageId', label: 'Page ID', type: 'string', required: false },
      { id: 'content', label: 'Content', type: 'string', required: false },
      { id: 'postId', label: 'Post ID', type: 'string', required: false },
    ],
    outputs: [
      { id: 'postId', label: 'Post ID', type: 'string' },
      { id: 'posts', label: 'Posts', type: 'array' },
      { id: 'response', label: 'API Response', type: 'object' },
    ],
    configSchema: {
      accessToken: { type: 'password', required: true },
      apiVersion: { type: 'text', default: 'v18.0' },
      timeout: { type: 'number', min: 1000, max: 300000, default: 30000 },
    },
  },

  // Calendar Nodes
  {
    id: 'calendar-google',
    name: 'Google Calendar',
    description: 'Create, read, and manage Google Calendar events',
    category: 'calendar',
    icon: '📅',
    color: '#4285F4',
    inputs: [
      { id: 'action', label: 'Action', type: 'string', required: true },
      { id: 'eventData', label: 'Event Data', type: 'object', required: false },
      { id: 'eventId', label: 'Event ID', type: 'string', required: false },
      { id: 'calendarId', label: 'Calendar ID', type: 'string', required: false },
      { id: 'timeMin', label: 'Start Time', type: 'string', required: false },
      { id: 'timeMax', label: 'End Time', type: 'string', required: false },
    ],
    outputs: [
      { id: 'event', label: 'Event', type: 'object' },
      { id: 'events', label: 'Events', type: 'array' },
      { id: 'eventId', label: 'Event ID', type: 'string' },
      { id: 'response', label: 'API Response', type: 'object' },
    ],
    configSchema: {
      accessToken: { type: 'password', required: true },
      refreshToken: { type: 'password', required: false },
      clientId: { type: 'text', required: true },
      clientSecret: { type: 'password', required: true },
      calendarId: { type: 'text', default: 'primary' },
      timezone: { type: 'text', default: 'UTC' },
    },
  },

  // Data & Storage Nodes
  {
    id: 'data-google-sheets',
    name: 'Google Sheets',
    description:
      'Advanced Google Sheets integration with read, write, search, and automation capabilities',
    category: 'data',
    icon: '📊',
    color: '#0F9D58',
    inputs: [
      { id: 'action', label: 'Action', type: 'string', required: true },
      { id: 'spreadsheetId', label: 'Spreadsheet ID', type: 'string', required: false },
      { id: 'sheetName', label: 'Sheet Name', type: 'string', required: false },
      { id: 'range', label: 'Range', type: 'string', required: false },
      { id: 'data', label: 'Data', type: 'any', required: false },
      { id: 'valueInputOption', label: 'Value Input Option', type: 'string', required: false },
      { id: 'useHeaderRow', label: 'Use Header Row', type: 'boolean', required: false },
      { id: 'includeRowNumbers', label: 'Include Row Numbers', type: 'boolean', required: false },
      { id: 'column', label: 'Column', type: 'any', required: false },
      { id: 'value', label: 'Value', type: 'any', required: false },
      { id: 'title', label: 'Title', type: 'string', required: false },
      { id: 'sheetId', label: 'Sheet ID', type: 'number', required: false },
      { id: 'updates', label: 'Updates', type: 'array', required: false },
      { id: 'formatting', label: 'Formatting', type: 'object', required: false },
      { id: 'rowIndexes', label: 'Row Indexes', type: 'array', required: false },
    ],
    outputs: [
      { id: 'data', label: 'Data', type: 'any' },
      { id: 'rowCount', label: 'Row Count', type: 'number' },
      { id: 'isEmpty', label: 'Is Empty', type: 'boolean' },
      { id: 'updatedRange', label: 'Updated Range', type: 'string' },
      { id: 'updatedRows', label: 'Updated Rows', type: 'number' },
      { id: 'affectedRange', label: 'Affected Range', type: 'string' },
      { id: 'affectedRows', label: 'Affected Rows', type: 'number' },
      { id: 'spreadsheetId', label: 'Spreadsheet ID', type: 'string' },
      { id: 'spreadsheetUrl', label: 'Spreadsheet URL', type: 'string' },
      { id: 'sheetId', label: 'Sheet ID', type: 'number' },
      { id: 'sheetName', label: 'Sheet Name', type: 'string' },
      { id: 'title', label: 'Title', type: 'string' },
      { id: 'sheets', label: 'Sheets', type: 'array' },
      { id: 'updatedRanges', label: 'Updated Ranges', type: 'array' },
      { id: 'totalUpdatedRows', label: 'Total Updated Rows', type: 'number' },
      { id: 'formattedRange', label: 'Formatted Range', type: 'string' },
      { id: 'action', label: 'Action Performed', type: 'string' },
    ],
    configSchema: {
      accessToken: { type: 'password', required: true },
      refreshToken: { type: 'password', required: false },
      clientId: { type: 'text', required: true },
      clientSecret: { type: 'password', required: true },
      spreadsheetId: { type: 'text', required: false },
    },
  },
  {
    id: 'trigger-google-sheets',
    name: 'Google Sheets Trigger',
    description: 'Triggers workflows based on Google Sheets changes',
    category: 'trigger',
    icon: '📊',
    color: '#0F9D58',
    inputs: [],
    outputs: [
      { id: 'newRows', label: 'New Rows', type: 'array' },
      { id: 'changedRows', label: 'Changed Rows', type: 'array' },
      { id: 'deletedRows', label: 'Deleted Rows', type: 'array' },
      { id: 'triggerType', label: 'Trigger Type', type: 'string' },
      { id: 'timestamp', label: 'Timestamp', type: 'string' },
    ],
    configSchema: {
      accessToken: { type: 'password', required: true },
      refreshToken: { type: 'password', required: false },
      clientId: { type: 'text', required: true },
      clientSecret: { type: 'password', required: true },
      spreadsheetId: { type: 'text', required: true },
      sheetName: { type: 'text', required: true },
      triggerType: {
        type: 'select',
        options: ['onNewRow', 'onRowChanged', 'onSheetChanged'],
        default: 'onNewRow',
      },
      checkInterval: { type: 'number', min: 1000, max: 3600000, default: 60000 },
      useHeaderRow: { type: 'boolean', default: true },
    },
  },
];
