export type Category = {
  id: string;
  name: string;
  accentHex: string;
  lightBg: string;
  darkBg: string;
  textOnBg: string;
  darkTextOnBg: string;
  lucideIcon: string;
  agentCount: number;
};

export type Agent = {
  id: string;
  name: string;
  description: string;
  categoryId: string;
  libs: string[];
  acceptedFiles: string[];
  suggestedQuestions: string[];
};

export const OFFICE_CATEGORIES: Category[] = [
  {
    id: 'docs',
    name: 'Documents',
    accentHex: '#534AB7',
    lightBg: '#EEEDFE',
    darkBg: '#26215C',
    textOnBg: '#3C3489',
    darkTextOnBg: '#CECBF6',
    lucideIcon: 'FileText',
    agentCount: 5,
  },
  {
    id: 'hr',
    name: 'HR & People',
    accentHex: '#1D9E75',
    lightBg: '#E1F5EE',
    darkBg: '#04342C',
    textOnBg: '#0F6E56',
    darkTextOnBg: '#9FE1CB',
    lucideIcon: 'Users',
    agentCount: 4,
  },
  {
    id: 'finance',
    name: 'Finance',
    accentHex: '#BA7517',
    lightBg: '#FAEEDA',
    darkBg: '#412402',
    textOnBg: '#854F0B',
    darkTextOnBg: '#FAC775',
    lucideIcon: 'Banknote',
    agentCount: 6,
  },
  {
    id: 'ops',
    name: 'Operations',
    accentHex: '#D85A30',
    lightBg: '#FAECE7',
    darkBg: '#4A1B0C',
    textOnBg: '#993C1D',
    darkTextOnBg: '#F5C4B3',
    lucideIcon: 'Settings',
    agentCount: 4,
  },
  {
    id: 'sales',
    name: 'Sales & Mktg',
    accentHex: '#378ADD',
    lightBg: '#E6F1FB',
    darkBg: '#042C53',
    textOnBg: '#185FA5',
    darkTextOnBg: '#B5D4F4',
    lucideIcon: 'TrendingUp',
    agentCount: 4,
  },
  {
    id: 'it',
    name: 'IT & Compliance',
    accentHex: '#639922',
    lightBg: '#EAF3DE',
    darkBg: '#173404',
    textOnBg: '#3B6D11',
    darkTextOnBg: '#C0DD97',
    lucideIcon: 'ShieldCheck',
    agentCount: 4,
  },
  {
    id: 'data',
    name: 'Data & Analytics',
    accentHex: '#D4537E',
    lightBg: '#FBEAF0',
    darkBg: '#4B1528',
    textOnBg: '#993556',
    darkTextOnBg: '#F4C0D1',
    lucideIcon: 'Database',
    agentCount: 6,
  },
];

export const OFFICE_AGENTS: Agent[] = [
  {
    id: 'word-analyst',
    name: 'Word Document Analyst',
    description: 'Analyze .docx files',
    categoryId: 'docs',
    libs: ['python-docx', 'pandas'],
    acceptedFiles: ['.docx'],
    suggestedQuestions: [
      'Extract all headings',
      'Find tables in document',
      'Summarize key sections',
    ],
  },
  {
    id: 'ppt-analyst',
    name: 'PowerPoint Analyst',
    description: 'Analyze .pptx files',
    categoryId: 'docs',
    libs: ['python-pptx', 'pandas'],
    acceptedFiles: ['.pptx'],
    suggestedQuestions: [
      'List all slides',
      'Find slides missing notes',
      'Extract all text content',
    ],
  },
  {
    id: 'email-analyzer',
    name: 'Email Batch Analyzer',
    description: 'Analyze email exports',
    categoryId: 'docs',
    libs: ['mailbox', 'pandas'],
    acceptedFiles: ['.mbox', '.csv'],
    suggestedQuestions: [
      'Top senders by volume',
      'Average response time',
      'Thread length distribution',
    ],
  },
  {
    id: 'transcript-analyzer',
    name: 'Meeting Transcript Analyzer',
    description: 'Process meeting transcripts',
    categoryId: 'docs',
    libs: ['re', 'pandas'],
    acceptedFiles: ['.txt', '.vtt'],
    suggestedQuestions: [
      'Extract action items',
      'Speaking time per person',
      'Unresolved questions',
    ],
  },
  {
    id: 'invoice-processor',
    name: 'Invoice & Receipt Processor',
    description: 'Extract data from invoices',
    categoryId: 'docs',
    libs: ['pdfplumber', 'pandas'],
    acceptedFiles: ['.pdf', '.csv'],
    suggestedQuestions: [
      'Total spend by vendor',
      'Flag duplicate invoices',
      'Overdue payment summary',
    ],
  },
  {
    id: 'payroll-analyst',
    name: 'Payroll Analyst',
    description: 'Analyze payroll data',
    categoryId: 'hr',
    libs: ['pandas', 'scipy'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Flag salary anomalies',
      'Department cost breakdown',
      'Headcount trend chart',
    ],
  },
  {
    id: 'attendance-analyzer',
    name: 'Attendance Analyzer',
    description: 'Process attendance exports',
    categoryId: 'hr',
    libs: ['pandas', 'seaborn'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Chronic absenteeism report',
      'Overtime hours by team',
      'Policy violation flags',
    ],
  },
  {
    id: 'recruitment-analyst',
    name: 'Recruitment Pipeline Analyst',
    description: 'Recruitment funnel analysis',
    categoryId: 'hr',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: [
      'Time-to-hire by role',
      'Offer acceptance rate',
      'Drop-off stage analysis',
    ],
  },
  {
    id: 'performance-review',
    name: 'Performance Review Aggregator',
    description: 'Aggregate review data',
    categoryId: 'hr',
    libs: ['pandas', 'sklearn'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Rating distribution chart',
      'Detect rater bias',
      'Performance band clusters',
    ],
  },
  {
    id: 'budget-actuals',
    name: 'Budget vs Actuals Analyzer',
    description: 'Compare budgets',
    categoryId: 'finance',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Variance by line item',
      'Flag overspent categories',
      'Project year-end position',
    ],
  },
  {
    id: 'expense-auditor',
    name: 'Expense Report Auditor',
    description: 'Audit expenses',
    categoryId: 'finance',
    libs: ['pandas', 'fuzzywuzzy'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Policy violation flags',
      'Duplicate submission check',
      'Top spenders ranking',
    ],
  },
  {
    id: 'ar-aging',
    name: 'AR Aging Analyst',
    description: 'Analyze receivables',
    categoryId: 'finance',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Bucket by age 0-30-60-90',
      'At-risk accounts list',
      'Collection rate trend',
    ],
  },
  {
    id: 'cashflow-forecast',
    name: 'Cash Flow Forecaster',
    description: 'Forecast cash flow',
    categoryId: 'finance',
    libs: ['statsmodels', 'pandas'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: [
      '30-day cash projection',
      'Detect seasonal patterns',
      'Compute runway weeks',
    ],
  },
  {
    id: 'payment-optimizer',
    name: 'Payments Optimizer',
    description: 'Optimize payment strategies',
    categoryId: 'finance',
    libs: ['pandas', 'numpy'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Identify early payment discounts',
      'Optimize payment timing',
      'Consolidate payments',
    ],
  },
  {
    id: 'vendor-spend',
    name: 'Vendor Spend Analyzer',
    description: 'Analyze vendor spend',
    categoryId: 'finance',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Rank vendors by spend',
      'Price variance across orders',
      'Single-source dependencies',
    ],
  },
  {
    id: 'project-timeline',
    name: 'Project Timeline Analyzer',
    description: 'Analyze project timelines',
    categoryId: 'ops',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: ['Schedule variance report', 'Overdue task list', 'Critical path blockers'],
  },
  {
    id: 'sla-compliance',
    name: 'SLA Compliance Analyzer',
    description: 'Check SLA compliance',
    categoryId: 'ops',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: [
      'SLA breach rate by tier',
      'First-response time avg',
      'Agent performance ranking',
    ],
  },
  {
    id: 'inventory-analyst',
    name: 'Inventory & Stock Analyst',
    description: 'Inventory insights',
    categoryId: 'ops',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Low-stock alert list',
      'ABC classification chart',
      'Turnover rate by SKU',
    ],
  },
  {
    id: 'supply-chain',
    name: 'Supply Chain Delay Tracker',
    description: 'Track supplier delays',
    categoryId: 'ops',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: [
      'Avg delay per supplier',
      'On-time delivery trend',
      'Delay pattern by weekday',
    ],
  },
  {
    id: 'sales-pipeline',
    name: 'Sales Pipeline Analyst',
    description: 'Analyze sales pipeline',
    categoryId: 'sales',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: ['Win rate by rep', 'Average deal size trend', 'Stage conversion funnel'],
  },
  {
    id: 'churn-analyzer',
    name: 'Customer Churn Analyzer',
    description: 'Analyze churn',
    categoryId: 'sales',
    libs: ['pandas', 'sklearn'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: [
      'Monthly churn rate',
      'High-risk customer segments',
      'Cohort retention curve',
    ],
  },
  {
    id: 'campaign-performance',
    name: 'Campaign Performance Analyzer',
    description: 'Evaluate campaigns',
    categoryId: 'sales',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: ['CPA by campaign', 'ROAS comparison chart', 'Underperformer flags'],
  },
  {
    id: 'survey-analyzer',
    name: 'Survey & Feedback Analyzer',
    description: 'Analyze surveys',
    categoryId: 'sales',
    libs: ['pandas', 'wordcloud'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'NPS score breakdown',
      'Promoter vs detractor split',
      'Top keyword frequency',
    ],
  },
  {
    id: 'access-rights',
    name: 'Access Rights Auditor',
    description: 'Audit access rights',
    categoryId: 'it',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: [
      'Flag excessive privileges',
      'Dormant account list',
      'Role distribution chart',
    ],
  },
  {
    id: 'license-tracker',
    name: 'Software License Tracker',
    description: 'Track software licenses',
    categoryId: 'it',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Installed vs licensed seats',
      'Cost per department',
      'Unused subscriptions',
    ],
  },
  {
    id: 'incident-analyzer',
    name: 'Incident & Downtime Analyzer',
    description: 'Analyze incidents',
    categoryId: 'it',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: ['MTTR by system', 'Incident frequency chart', 'Root cause distribution'],
  },
  {
    id: 'csv-analyst',
    name: 'CSV Data Analyst',
    description: 'Analyze CSVs',
    categoryId: 'data',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: [
      'Show summary statistics',
      'Plot histogram of all columns',
      'Which column has most nulls?',
    ],
  },
  {
    id: 'sql-analyst',
    name: 'SQL Database Analyst',
    description: 'Analyze SQL databases',
    categoryId: 'data',
    libs: ['sqlalchemy', 'pandas'],
    acceptedFiles: ['.db', '.sql'],
    suggestedQuestions: ['Show all tables', 'Row count per table', 'Find null-heavy columns'],
  },
  {
    id: 'excel-analyst',
    name: 'Excel Multi-Sheet Analyst',
    description: 'Analyze Excel files',
    categoryId: 'data',
    libs: ['openpyxl', 'pandas'],
    acceptedFiles: ['.xlsx', '.xls'],
    suggestedQuestions: ['List all sheets', 'Cross-sheet totals', 'Pivot table summary'],
  },
  {
    id: 'financial-data',
    name: 'Financial Data Analyst',
    description: 'Financial time series',
    categoryId: 'data',
    libs: ['yfinance', 'ta'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: ['Plot price history', 'Compute RSI indicator', 'Bollinger band chart'],
  },
  {
    id: 'ml-modeler',
    name: 'Statistical ML Modeler',
    description: 'Train simple models',
    categoryId: 'data',
    libs: ['sklearn', 'matplotlib'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: ['Train regression model', 'Feature importance chart', 'Confusion matrix'],
  },
  {
    id: 'log-analyst',
    name: 'Log File Analyst',
    description: 'Analyze log files',
    categoryId: 'data',
    libs: ['re', 'pandas'],
    acceptedFiles: ['.log', '.txt'],
    suggestedQuestions: ['Error frequency by hour', 'Top error types', 'Anomaly spike detection'],
  },
  {
    id: 'image-processor',
    name: 'Image Processing Agent',
    description: 'Process images',
    categoryId: 'data',
    libs: ['Pillow', 'opencv'],
    acceptedFiles: ['.png', '.jpg'],
    suggestedQuestions: ['Analyze histogram', 'Compare two images', 'Detect edges'],
  },
  {
    id: 'pdf-extractor',
    name: 'PDF Data Extractor',
    description: 'Extract from PDFs',
    categoryId: 'data',
    libs: ['pdfplumber', 'pandas'],
    acceptedFiles: ['.pdf'],
    suggestedQuestions: ['Extract all tables', 'Page-by-page text', 'Find all numbers'],
  },
  {
    id: 'json-analyst',
    name: 'JSON & API Analyst',
    description: 'Analyze JSON',
    categoryId: 'data',
    libs: ['pandas', 'json'],
    acceptedFiles: ['.json'],
    suggestedQuestions: ['Flatten nested structure', 'Key frequency analysis', 'Find null values'],
  },
  {
    id: 'timeseries-forecaster',
    name: 'Time Series Forecaster',
    description: 'Forecast time series',
    categoryId: 'data',
    libs: ['prophet', 'pandas'],
    acceptedFiles: ['.csv'],
    suggestedQuestions: ['Decompose trend & seasonality', '30-day forecast', 'Detect anomalies'],
  },
  {
    id: 'multifile-correlation',
    name: 'Multi-File Correlation Agent',
    description: 'Correlate files',
    categoryId: 'data',
    libs: ['pandas', 'matplotlib'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: [
      'Join two files on key',
      'Cross-file correlation matrix',
      'Merge and summarize',
    ],
  },
  {
    id: 'data-quality',
    name: 'Data Quality Agent',
    description: 'Check data quality',
    categoryId: 'data',
    libs: ['pandas', 'great_expectations'],
    acceptedFiles: ['.csv', '.xlsx'],
    suggestedQuestions: ['Duplicate row report', 'Outlier detection', 'Type mismatch flags'],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return OFFICE_CATEGORIES.find(c => c.id === id);
}

export function getAgentById(id: string): Agent | undefined {
  return OFFICE_AGENTS.find(a => a.id === id);
}
